# Generated by Django 4.0.3 on 2022-12-01 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0006_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
